routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::any('/register', 'HomeController@index')->name('register');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'Search@search')->name('search');
Route::post('/search', 'Search@search')->name('search');
Route::get('/search-more', 'Search@searchaction')->name('searchaction');
Route::post('/search', 'Search@search')->name('search');
Route::resource('/tags', 'TagsController');
Route::resource('/staff', 'UserController');
Route::resource('/people', 'PersonController');
Route::resource('/contact-categories', 'PersonTypeController');
Route::resource('/organization', 'OrganizationController');
Route::resource('/events', 'EventController');
Route::resource('/skills', 'SkillController');
Route::resource('/interests', 'InterestController');
Route::resource('/event/event-dates', 'EventDateController');
Route::get('/event/event-date/export/attendees/{event}', 'EventDateController@export')->name('export-event-attendees');
Route::post('/event/event-date/spot/attendees/{event}', 'EventDateController@spot')->name('attendance.spot');
Route::resource('/event-date/attendance', 'EventAttendanceController');
Route::resource('/event-date/speakers', 'EventSpeakersController');
Route::resource('settings', 'SettingsController');

// Excel Import

Route::post('/import/people', 'PersonController@import')->name('people.import');
Route::post('/import/organizations', 'OrganizationController@import')->name('organization.import');
Route::post('/import/events', 'EventController@import')->name('event.import');
Route::post('/import/event-dates', 'EventDateController@import')->name('event-dates.import');
Route::post('/import/event-dates/attendance', 'EventAttendanceController@import')->name('event-dates.attandance.import');

app/tags.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tags extends Model
{
    //
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\tags;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param  \App\tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function index(tags $tags)
    {
        $tags   = $tags->paginate(10);
        return view('tags.index',['tags'=>$tags]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function show(tags $tags,$tag)
    {
        $tags   =  $tags->find($tag);
        $events = \App\Event::where("tags","LIKE","%$tags->tag%")->get();
        $people = \App\Person::where("tags","LIKE","%$tags->tag%")->get();
        return view('tags.show',['tag'=>$tags,"events"=>$events,"people"=>$people]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function edit(tags $tags)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, tags $tags)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function destroy(tags $tags)
    {
        //
    }
}

resources/views/tags/create.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form action="{{route('skills.store')}}" method="POST" class="card">
                @csrf
                <div class="card-header">
                    <a href="{{route('skills.index')}}" class="btn btn-outline-secondary btn-sm float-right">Cancel</a>
                    Add Skill
                </div>
                <div class="card-body">
                   <div class="form-group">
                       <label for="skill">Title</label>
                       <input type="text" id="skill" name="skill" class="form-control">
                   </div>
                   <div class="form-group">
                       <label for="parent">Parent</label>
                       <select id="parent" name="parent" class="form-control selectjs-basic-single">
                           <option value="0">No Parent</option>
                           @forelse ($skills as $skill)
                               <option value="{{$skill->id}}">{{$skill->skill}}</option>
                           @empty
                               
                           @endforelse
                       </select>
                   </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="card" action="{{route('organization.update',$organization->id)}}" method="POST">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <div class="card-header">Edit {{$organization->name}}
                    <div class="float-right">
                        <a href="{{route('organization.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                    </div>
                </div>
                <div class="card-body row">
                    <div class="form-group col-sm-12">
                        <label for="org_name">Name</label>
                        <input type="text" name="name" id="org_name" class="form-control" value="@if(old('name')) {{old('name')}} @else {{$organization->name}} @endif">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_location">Location</label>
                        <input type="text" name="location" id="org_location" class="form-control" value="@if(old('location')) {{old('location')}} @else {{$organization->location}}  @endif">
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_category">Category</label>
                        <select name="category" id="org_category" class="form-control">
                            <option @if(old('category') == 'School' || $organization->type =='School') selected @endif value="School">School</option>
                            <option @if(old('category') == 'College' || $organization->type =='College') selected @endif value="College">College</option>
                            <option @if(old('category') == 'Institution' || $organization->type =='Institution') selected @endif value="Institution">Institution</option>
                            <option @if(old('category') == 'Non-Profit' || $organization->type =='Non-Profit') selected @endif value="Non-Profit">Non-Profit</option>
                            <option @if(old('category') == 'Company' || $organization->type =='Company') selected @endif value="Company">Company</option>
                            <option @if(old('category') == 'Startup' || $organization->type =='Startup') selected @endif value="Startup">Startup</option>
                            <option @if(old('category') == 'Goverment' || $organization->type =='Goverment') selected @endif value="Goverment">Goverment</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_person">Contact Endpoint</label>
                        <select name="person" id="org_person" class="form-control">
                            @foreach ($people as $person)
                                <option @if(old('person') == $person->id || $organization->person == $person->id ) selected @endif value="$person->id">{{$person->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_tags">Tags</label>
                        <input type="text" name="tags" id="org_tags" class="form-control typeahead" value="@if(old('tags')) {{old('tags')}} @else {{$organization->tags}}  @endif">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.internal')

@section('content')
<div class="page-header">
    <a href="{{route('tags.create')}}" class="btn btn-outline-info btn-sm float-right">Add Tag</a>
    <h3 class="mb-2">Tags <i>({{$tags->total()}})</i></h3>
    <div class="page-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}" class="breadcrumb-link">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="" class="breadcrumb-link">Tags</a></li>
            </ol>
        </nav>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {{$tags->links()}}
        </div>
        <div class="col-sm-12 card">
            <table class="table sm">
                <thead>
                    <tr>
                        <th>Tag</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($tags as $tag)
                        <tr>
                            <th>
                               <a href="{{route('tags.show',[$tag->id])}}">{{$tag->tag}}</a>
                            </th>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/tags/show.blade.php
@extends('layouts.internal')
@section('title',$tag->tag)

@section('content')
<div class="page-header">
    <h3 class="mb-2">{{$tag->tag}}</i></h3>
    <div class="page-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}" class="breadcrumb-link">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{route('tags.index')}}" class="breadcrumb-link">Tags</a></li>
                <li class="breadcrumb-item"><a href="" class="breadcrumb-link">{{$tag->tag}}</a></li>
            </ol>
        </nav>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card card-body">
                <h5>Events</h5>
                <table class="table sm">
                    <thead>
                        <tr>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($events as $event)
                        <tr>
                            <th><a href="{{route('events.show',[$event->id])}}">{{$event->name}}</a></th>
                        </tr>
                        @empty
                        <tr>
                            <th>No Events</th>
                        </tr>   
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 ">
            <div class="card card-body">
                <h5>People</h5>
                <table class="table sm">
                    <thead>
                        <tr>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($people as $person)
                        <tr>
                            <th><a href="{{route('people.show',[$person->id])}}">{{$person->name}}</a></th>
                        </tr>
                        @empty
                        <tr>
                            <th>No People</th>
                        </tr>   
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection