routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::any('/register', 'HomeController@index')->name('register');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'Search@search')->name('search');
Route::post('/search', 'Search@search')->name('search');
Route::get('/search-more', 'Search@searchaction')->name('searchaction');
Route::post('/search', 'Search@search')->name('search');
Route::resource('/tags', 'TagsController');
Route::resource('/staff', 'UserController');
Route::resource('/people', 'PersonController');
Route::resource('/contact-categories', 'PersonTypeController');
Route::resource('/organization', 'OrganizationController');
Route::resource('/events', 'EventController');
Route::resource('/skills', 'SkillController');
Route::resource('/interests', 'InterestController');
Route::resource('/event/event-dates', 'EventDateController');
Route::get('/event/event-date/export/attendees/{event}', 'EventDateController@export')->name('export-event-attendees');
Route::post('/event/event-date/spot/attendees/{event}', 'EventDateController@spot')->name('attendance.spot');
Route::resource('/event-date/attendance', 'EventAttendanceController');
Route::resource('/event-date/speakers', 'EventSpeakersController');
Route::resource('settings', 'SettingsController');

// Excel Import

Route::post('/import/people', 'PersonController@import')->name('people.import');
Route::post('/import/organizations', 'OrganizationController@import')->name('organization.import');
Route::post('/import/events', 'EventController@import')->name('event.import');
Route::post('/import/event-dates', 'EventDateController@import')->name('event-dates.import');
Route::post('/import/event-dates/attendance', 'EventAttendanceController@import')->name('event-dates.attandance.import');

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $fillable = ['name','email','mobile','gender','city','state','country','tags','position','organization','type'];
    
    public function Organization()
    {
        return $this->hasOne("App\Organization","id","organization");
    }
    public function Events()
    {
        return $this->hasMany('App\EventAttendance', 'person','id');
    }
    public function Category()
    {
        return $this->hasOne("App\PersonType","id","type");
    }
    public function Skills()
    {
        return $this->hasMany("App\PersonSkill","person","id");
    }
    public function Interests()
    {
        return $this->hasMany("App\PersonInterest","person","id");
    }
    public function CategoryName()
    {
        if($this->Category){
            return $this->Category->category;
        }
        else{
            return "Category not Assigned";
        }
    }
}

app/PersonType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PersonType extends Model
{
    //
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Person;
use App\Organization;
use App\Skill;
use App\Interest;
use App\PersonType;
use App\PersonSkill;
use App\PersonInterest;
use App\tags;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Importer;


class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $people = Person::all();
        return view("people.index",['people'=>$people]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organizations = Organization::all();
        $skills = Skill::where('parent',0)->get();
        $interests = Interest::where('parent',0)->get();
        $types = PersonType::all();
        return view("people.create",['organizations'=>$organizations,'skills'=>$skills,'types'=>$types,'interests'=>$interests]);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "name"=>"required",
            "email"=>"required|unique:people|string|email",
            "mobile"=>"required",
            "gender"=>"required"
        ]);
        $person = new Person;
        $person->name = $request->name;
        $person->email = $request->email;
        $person->mobile = $request->mobile;
        $person->gender = $request->gender;
        $person->dob = Carbon::parse($request->dob);
        $person->organization = $request->organization;
        $person->position = $request->position;
        $person->type = $request->profession_type;
        $person->data = $request->data;
        $person->city = $request->city;
        $person->state = $request->state;
        $person->country = $request->country;
        $person->tags = $request->tags;
        $person->save();
        if($request->skills){
            foreach($request->skills as $skill){
                $sk = new \App\PersonSkill;
                $sk->skill = $skill;
                $sk->person = $person->id;
                $sk->save();
            }
        }
        if($request->interests){
            foreach($request->interests as $interest){
                $sk = new \App\PersonInterest;
                $sk->interest = $interest;
                $sk->person = $person->id;
                $sk->save();
            }
        }
        $request->tags = trim($request->tags);
        foreach(explode(',',$request->tags) as $tag){
            $fs = tags::where('tag',$tag)->first();
            if(!$fs){
                $fd = new tags;
                $fd->tag = $tag;
                $fd->save();
            }
        }
        return redirect()->back()->with(['success'=>"$person->name Added"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function show(Person $person)
    {
        return view("people.show",['person'=>$person]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function edit(Person $person)
    {
        $organizations = Organization::all();
        $skills = Skill::where('parent',0)->get();
        $interests = Interest::where('parent',0)->get();
        $types = PersonType::all();
        return view("people.edit",['person'=>$person,'organizations'=>$organizations,'skills'=>$skills,'types'=>$types,'interests'=>$interests]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Person $person)
    {
        $request->validate([
            "name"=>"required",
            "email"=>"required|unique:people,email,$person->id|string|email",
            "mobile"=>"required",
            "gender"=>"required"
        ]);
        $person->name = $request->name;
        $person->email = $request->email;
        $person->mobile = $request->mobile;
        $person->gender = $request->gender;
        $person->dob = Carbon::parse($request->dob);
        $person->organization = $request->organization;
        $person->position = $request->position;
        $person->type = $request->profession_type;
        $person->data = $request->data;
        $person->city = $request->city;
        $person->state = $request->state;
        $person->country = $request->country;
        $person->tags = $request->tags;
        $person->save();
        PersonSkill::where('person',$person->id)->delete();
        PersonInterest::where('person',$person->id)->delete();
        if($request->skills){
            foreach($request->skills as $skill){
                $din = PersonSkill::where('person',$person->id)->where('skill',$skill)->first();
                if(!$din){
                    $sk = new PersonSkill;
                    $sk->skill = $skill;
                    $sk->person = $person->id;
                    $sk->save();
                }
            }
        }
        if($request->interests){
            foreach($request->interests as $interest){
                $sk = new PersonInterest;
                $sk->interest = $interest;
                $sk->person = $person->id;
                $sk->save();
            }
        }
        $request->tags = trim($request->tags);
        if(isset($request->tags) && $request->tags !=="" && !empty($request->tags)){
            foreach(explode(',',$request->tags) as $tag){
                $fs = tags::where('tag',$tag)->first();
                if(!$fs){
                    $fd = new tags;
                    $fd->tag = $tag;
                    $fd->save();
                }
            }
        }
        return redirect()->back()->with(['success'=>"$person->name Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function destroy(Person $person)
    {
        //
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function import(Request $request)
    {
        $file   = $request->file('upload');
        $fl     = $file->move('storage/temp',$file->getClientOriginalName());
        $excel = Importer::make('Csv');
        $excel->load($fl);
        $collection = $excel->getCollection();
        $fields     = $collection[0];
        $data       = [];
        for ($i=1; $i <count($collection) ; $i++) {
            $data[$i] = [];
            for ($s=0; $s <count($fields) ; $s++) {
                $data[$i][$fields[$s]] = $collection[$i][$s];
            }
        }
        for ($i=0; $i < count($data); $i++) {
            if(isset($data[$i]['email'])){
                $person = Person::where("email",trim($data[$i]['email']))->orWhere("mobile",trim($data[$i]['mobile']))->first();
                /*
                ** Check if Person Already Defined 
                */
                if(!$person){
                    /*
                    ** Check if type is assigned
                    */
                    if(isset($data[$i]['type'])){
                        $person_type = PersonType::where("category",$data[$i]['type'])->first();
                        if($person_type){
                            $data[$i]['type'] = $person_type->id;
                        }
                        else{
                            $data[$i]['type'] = 1;
                        }
                    }
                    /*
                    ** Check if organization is assigned
                    */
                    if(isset($data[$i]['organization'])){
                        $organization = Organization::where("name",$data[$i]['organization'])->first();
                        if($organization){
                            $data[$i]['organization'] = $organization->id;
                        }
                        else{
                            $data[$i]['organization'] = 0;
                        }
                    }
                    else{
                        $data[$i]['organization'] = 0;
                    }
                    /*
                    ** Check if dob is assigned
                    */
                    if(isset($data[$i]['dob'])){
                        $data[$i]['dob'] = Carbon::parse($data[$i]['dob']);
                    }
                    /*
                    ** Check if Tags are assigned
                    */
                    if(isset($data[$i]['tags']) && $data[$i]['tags'] !=="" && !empty($data[$i]['tags'])){
                        $data[$i]['tags'] = trim($data[$i]['tags']);
                        foreach(explode(',',$data[$i]['tags']) as $tag){
                            $fs = tags::where('tag',$tag)->first();
                            if(!$fs){
                                $fd = new tags;
                                $fd->tag = $tag;
                                $fd->save();
                            }
                        }
                    }
                }
                else{
                    unset($data[$i]);
                }
            }            
        }
        /*
        ** Create All Users
        */
        foreach ($data as $key) {
            $person = Person::where("email",trim($key['email']))->first();
            if(!$person){
                $person = new Person;
                var_dump($key);

resources/views/people/categories/create.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="card" action="{{route('contact-categories.store')}}" method="POST">
                @csrf
                <div class="card-header">Create Contact Category
                    <div class="float-right">
                        <a href="{{route('contact-categories.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                    </div>
                </div>
                <div class="card-body row">
                    <div class="form-group col-sm-12">
                        <label for="org_category">Name</label>
                        <input type="text" name="category" id="org_category" class="form-control" required value="@if(old('category')) {{old('category')}} @endif">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/people/categories/edit.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="card" action="{{route('organization.update',$organization->id)}}" method="POST">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <div class="card-header">Edit {{$organization->name}}
                    <div class="float-right">
                        <a href="{{route('organization.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                    </div>
                </div>
                <div class="card-body row">
                    <div class="form-group col-sm-12">
                        <label for="org_name">Name</label>
                        <input type="text" name="name" id="org_name" class="form-control" value="@if(old('name')) {{old('name')}} @else {{$organization->name}} @endif">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_location">Location</label>
                        <input type="text" name="location" id="org_location" class="form-control" value="@if(old('location')) {{old('location')}} @else {{$organization->location}}  @endif">
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_category">Category</label>
                        <select name="category" id="org_category" class="form-control">
                            <option @if(old('category') == 'School' || $organization->type =='School') selected @endif value="School">School</option>
                            <option @if(old('category') == 'College' || $organization->type =='College') selected @endif value="College">College</option>
                            <option @if(old('category') == 'Institution' || $organization->type =='Institution') selected @endif value="Institution">Institution</option>
                            <option @if(old('category') == 'Non-Profit' || $organization->type =='Non-Profit') selected @endif value="Non-Profit">Non-Profit</option>
                            <option @if(old('category') == 'Company' || $organization->type =='Company') selected @endif value="Company">Company</option>
                            <option @if(old('category') == 'Startup' || $organization->type =='Startup') selected @endif value="Startup">Startup</option>
                            <option @if(old('category') == 'Goverment' || $organization->type =='Goverment') selected @endif value="Goverment">Goverment</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_person">Contact Endpoint</label>
                        <select name="person" id="org_person" class="form-control">
                            @foreach ($people as $person)
                                <option @if(old('person') == $person->id || $organization->person == $person->id ) selected @endif value="$person->id">{{$person->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_tags">Tags</label>
                        <input type="text" name="tags" id="org_tags" class="form-control typeahead" value="@if(old('tags')) {{old('tags')}} @else {{$organization->tags}}  @endif">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/people/categories/index.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">People Categories
                    <a href="{{route('contact-categories.create')}}" class="btn btn-sm btn-outline-secondary float-right">Create New</a>
                </div>
                <table class="table table-sm">
                    <thead class="table-secondary">
                        <tr>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($categories as $category)
                            <tr>
                                <th><a href="{{route('contact-categories.show',$category->id)}}">{{$category->category}}</a></th>
                                {{-- <th>{{$category->category}}</th> --}}
                            </tr>
                        @empty
                            <tr>
                                <th colspan="4" class="text-center">No categories</th>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/people/categories/show.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @csrf
                <div class="card-header"> {{$organization->name}}
                    <div class="float-right">
                        <a href="{{route('organization.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                        <a href="{{route('organization.edit',$organization->id)}}" class="btn btn-sm btn-outline-primary">Edit</a>
                    </div>
                </div>
                <div class="card-body">
                    <strong>About {{$organization->name}} </strong>
                    <table class="table">
                        <tr>
                            <th>Name</th>
                            <td>{{$organization->name}}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{$organization->type}}</td>
                        </tr>
                        <tr>
                            <th>Location</th>
                            <td>{{$organization->location}}</td>
                        </tr>
                        <tr>
                            <th>Tags</th>
                            <td>
                                @forelse (explode(",",$organization->tags) as $item)
                                    <span class="badge badge-success">{{$item}}</span>
                                @empty
                                    
                                @endforelse
                            </td>
                        </tr>
                    </table>
                    <strong>People in {{$organization->name}} </strong>
                    <table class="table table-sm">
                        <thead class="table-secondary">
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Position</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($organization->Employees as $employee)
                                <tr>
                                    <th><a href="{{route('people.show',$employee->id)}}">{{$employee->name}}</a></th>
                                    <td>{{$employee->email}}</td>
                                    <td>{{$employee->mobile}}</td>
                                    <td>{{$employee->profession_type}} ({{$employee->profession}})</td>
                                </tr>
                            @empty
                                <tr>
                                    <th colspan="4" class="text-center">No people attached to this organization</th>
                                </tr>
                            @endforelse
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection