routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::any('/register', 'HomeController@index')->name('register');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'Search@search')->name('search');
Route::post('/search', 'Search@search')->name('search');
Route::get('/search-more', 'Search@searchaction')->name('searchaction');
Route::post('/search', 'Search@search')->name('search');
Route::resource('/tags', 'TagsController');
Route::resource('/staff', 'UserController');
Route::resource('/people', 'PersonController');
Route::resource('/contact-categories', 'PersonTypeController');
Route::resource('/organization', 'OrganizationController');
Route::resource('/events', 'EventController');
Route::resource('/skills', 'SkillController');
Route::resource('/interests', 'InterestController');
Route::resource('/event/event-dates', 'EventDateController');
Route::get('/event/event-date/export/attendees/{event}', 'EventDateController@export')->name('export-event-attendees');
Route::post('/event/event-date/spot/attendees/{event}', 'EventDateController@spot')->name('attendance.spot');
Route::resource('/event-date/attendance', 'EventAttendanceController');
Route::resource('/event-date/speakers', 'EventSpeakersController');
Route::resource('settings', 'SettingsController');

// Excel Import

Route::post('/import/people', 'PersonController@import')->name('people.import');
Route::post('/import/organizations', 'OrganizationController@import')->name('organization.import');
Route::post('/import/events', 'EventController@import')->name('event.import');
Route::post('/import/event-dates', 'EventDateController@import')->name('event-dates.import');
Route::post('/import/event-dates/attendance', 'EventAttendanceController@import')->name('event-dates.attandance.import');

app/Organization.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    protected $fillable = ['name','location','type','tags'];
    
    public function Person()
    {
        return $this->hasOne("App\Person","id","person");
    }
    public function Employees()
    {
        return $this->hasMany("App\Person","organization","id");
    }
    public function Events()
    {
        return $this->hasMany("App\Event","organization","id");
    }
}

app/Http/Controllers/OrganizationController.php
<?php

namespace App\Http\Controllers;

use App\Organization;
use App\Person;
use App\tags;
use Illuminate\Http\Request;
use Importer;


class OrganizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organizations = Organization::paginate(20);
        return view('organizations.index',['organizations'=>$organizations]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $people = Person::all();
        return view('organizations.create',['people'=>$people]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "name"=>"required",
            "category"=>"required",
        ]);
        $organization = new Organization;
        $organization->name = $request->name;
        $organization->location = $request->location;
        $organization->type = $request->category;
        $organization->tags = $request->tags;
        $organization->person = $request->person;
        $organization->email = $request->email;
        $organization->phone = $request->phone;
        $organization->save();
        foreach(explode(',',$request->tags) as $tag){
            $fs = tags::where('tag',$tag)->first();
            if(!$fs){
                $fd = new tags;
                $fd->tag = $tag;
                $fd->save();
            }
        }
        return redirect()->back()->with(['success'=>"Added New Organization"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function show(Organization $organization)
    {
        return view('organizations.show',['organization'=>$organization]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function edit(Organization $organization)
    {
        $people = Person::all();
        return view('organizations.edit',['organization'=>$organization,'people'=>$people]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Organization $organization)
    {
        $request->validate([
            "name"=>"required",
            "category"=>"required",
        ]);
        $organization->name = $request->name;
        $organization->location = $request->location;
        $organization->type = $request->category;
        $organization->tags = $request->tags;
        $organization->email = $request->email;
        $organization->phone = $request->phone;
        $organization->person = $request->person;
        $organization->save();
        foreach(explode(',',$request->tags) as $tag){
            $fs = tags::where('tag',$tag)->first();
            if(!$fs){
                $fd = new tags;
                $fd->tag = $tag;
                $fd->save();
            }
        }
        return redirect()->back()->with(['success'=>"Organization updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function destroy(Organization $organization)
    {
        //
    }
    public function import(Request $request)
    {
        $file   = $request->file('upload');
        $fl     = $file->move('storage/temp',$file->getClientOriginalName());
        $excel = Importer::make('Csv');
        $excel->load($fl);
        $collection = $excel->getCollection();
        $fields     = $collection[0];
        $data       = [];
        for ($i=1; $i <count($collection) ; $i++) {
            $data[$i] = [];
            for ($s=0; $s <count($fields) ; $s++) {
                $data[$i][$fields[$s]] = $collection[$i][$s];
            }
        }
        foreach($data as $dat){
            $organization = new Organization;
            foreach ($dat as $key => $value) {
                if($key == 'person'){
                    $ps = Person::where('email',$value)->first();
                    if($ps){
                        $organization->{$key} = $ps->id;
                    }
                }
                elseif($key == 'tags'){
                    foreach(explode(',',$value) as $tag){
                        $fs = tags::where('tag',$tag)->first();
                        if(!$fs){
                            $fd = new tags;
                            $fd->tag = $tag;
                            $fd->save();
                        }
                    }
                    $person->{$key} = $value;
                }
                else{
                    $organization->{$key} = $value;
                }
            }
            $organization->save();
        }
        unlink($fl);
        return redirect()->back()->with('success', 'Upload and Import Sucess!');
    }
}

resources/views/organizations/create.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="card" action="{{route('organization.store')}}" method="POST">
                @csrf
                <div class="card-header">Create Organization
                    <div class="float-right">
                        <a href="{{route('organization.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                    </div>
                </div>
                <div class="card-body row">
                    <div class="form-group col-sm-12">
                        <label for="org_name">Name</label>
                        <input type="text" name="name" id="org_name" class="form-control" required value="@if(old('name')) {{old('name')}} @endif">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_location">Location</label>
                        <input type="text" name="location" id="org_location" class="form-control" value="@if(old('location')) {{old('location')}} @endif">
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_category">Category</label>
                        <select name="category" id="org_category" class="form-control selectjs-basic-single">
                            <option @if(old('category') == 'School') selected @endif value="School">School</option>
                            <option @if(old('category') == 'College') selected @endif value="College">College</option>
                            <option @if(old('category') == 'Institution') selected @endif value="Institution">Institution</option>
                            <option @if(old('category') == 'Non-Profit') selected @endif value="Non-Profit">Non-Profit</option>
                            <option @if(old('category') == 'Company') selected @endif value="Company">Company</option>
                            <option @if(old('category') == 'Startup') selected @endif value="Startup">Startup</option>
                            <option @if(old('category') == 'Goverment') selected @endif value="Goverment">Goverment</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_person">Contact Endpoint</label>
                        <select name="person" id="org_person" class="form-control">
                            <option value="" selected>No Organization</option>
                            @foreach ($people as $person)
                                <option @if(old('person') == $person->id) selected @endif value="$person->id">{{$person->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_email">Email</label>
                        <input type="email" name="email" id="org_email" class="form-control" value="{{old('email')}}">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_phone">Phone</label>
                        <input type="text" name="phone" id="org_phone" class="form-control" value="{{old('phone')}}">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_tags">Tags</label>
                        <input type="text" name="tags" id="org_tags" class="form-control typeahead" value="{{old('tags')}}">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/organizations/edit.blade.php
@extends('layouts.internal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="card" action="{{route('organization.update',$organization->id)}}" method="POST">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <div class="card-header">Edit {{$organization->name}}
                    <div class="float-right">
                        <a href="{{route('organization.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                    </div>
                </div>
                <div class="card-body row">
                    <div class="form-group col-sm-12">
                        <label for="org_name">Name</label>
                        <input type="text" name="name" id="org_name" class="form-control" value="@if(old('name')) {{old('name')}} @else {{$organization->name}} @endif">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_location">Location</label>
                        <input type="text" name="location" id="org_location" class="form-control" value="@if(old('location')) {{old('location')}} @else {{$organization->location}}  @endif">
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_category">Category</label>
                        <select name="category" id="org_category" class="form-control">
                            <option @if(old('category') == 'School' || $organization->type =='School') selected @endif value="School">School</option>
                            <option @if(old('category') == 'College' || $organization->type =='College') selected @endif value="College">College</option>
                            <option @if(old('category') == 'Institution' || $organization->type =='Institution') selected @endif value="Institution">Institution</option>
                            <option @if(old('category') == 'Non-Profit' || $organization->type =='Non-Profit') selected @endif value="Non-Profit">Non-Profit</option>
                            <option @if(old('category') == 'Company' || $organization->type =='Company') selected @endif value="Company">Company</option>
                            <option @if(old('category') == 'Startup' || $organization->type =='Startup') selected @endif value="Startup">Startup</option>
                            <option @if(old('category') == 'Goverment' || $organization->type =='Goverment') selected @endif value="Goverment">Goverment</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_person">Contact Endpoint</label>
                        <select name="person" id="org_person" class="form-control">
                            <option @if(old('person') == "" || $organization->person == "" ) selected @endif selected>No Organization</option>
                            @foreach ($people as $person)
                                <option @if(old('person') == $person->id || $organization->person == $person->id ) selected @endif value="{{$person->id}}">{{$person->name}} {{$person->email}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_email">Email</label>
                        <input type="email" name="email" id="org_email" class="form-control" value="@if(old('email')) {{old('email')}} @else {{$organization->email}}  @endif">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_phone">Phone</label>
                        <input type="text" name="phone" id="org_phone" class="form-control" value="@if(old('phone')) {{old('phone')}} @else {{$organization->phone}}  @endif">
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="org_tags">Tags</label>
                        <input type="text" name="tags" id="org_tags" class="form-control typeahead" value="@if(old('tags')) {{old('tags')}} @else {{$organization->tags}}  @endif">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/organizations/index.blade.php
@extends('layouts.internal')
@section('title',"Organizations")
@section('content')
<div class="page-header">
   <h3 class="mb-2">Organizations <i>({{$organizations->total()}})</i></h3>
   <div class="page-breadcrumb">
       <nav aria-label="breadcrumb">
           <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="{{route('home')}}" class="breadcrumb-link">Dashboard</a></li>
               <li class="breadcrumb-item"><a href="{{route('organization.index')}}" class="breadcrumb-link">Organizations</a></li>
           </ol>
       </nav>
   </div>
</div>
<div class="container">
    <div class="row" id="people-section">
        <div class="col-sm-12 col-md-10">
            <div class="card table-responsive card-body">
                <table class="table table-sm">
                    <thead class="table-secondary">
                        <tr>
                            <th>Name</th>
                            <th>Location</th>
                            <th>No of People</th>
                            <th>Email</th>
                            <th>Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($organizations as $organization)
                            <tr>
                                <th><a href="{{route('organization.show',$organization->id)}}">{{$organization->name}}</a></th>
                                <th>{{$organization->location}}</th>
                                <th>{{$organization->Employees->count()}}</th>
                                <th>{{$organization->email}}</th>
                                <th>{{$organization->phone}}</th>
                            </tr>
                        @empty
                            <tr>
                                <th colspan="4" class="text-center">No organizations</th>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="py-1"></div>
                <div class="card-footer">
                    {{$organizations->links()}}
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-2">
            <div class="card card-body">
                <a href="{{route('organization.create')}}" class="btn btn-sm btn-outline-secondary">Create New</a>
                <br>
                <a href="#organization-upload-modal" data-toggle="modal" data-target="#organization-upload-modal" class="btn btn-sm btn-outline-primary">Upload CSV</a>
                <br>
                <a href="{{Storage::url('downloads/organization.csv')}}" class="btn btn-sm btn-outline-info">Template</a>
                </div>
            </div>
        </div>
    </div>
    <form action="{{route('organization.import')}}" method="POST" class="modal" id="organization-upload-modal" enctype="multipart/form-data">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    @csrf
                    <div class="form-group">
                        <input type="file" accept=".csv" required  name="upload" class="form-control">
                    </div>
                    <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-info btn-sm" type="submit">Upload</button>
            </div>
        </div>
    </form>
@endsection

resources/views/organizations/show.blade.php
@extends('layouts.internal')
@section('title',$organization->name)
@section('content')
<div class="page-header">
   <h3 class="mb-2">{{$organization->name}}</small></h3>
   <div class="page-breadcrumb">
       <nav aria-label="breadcrumb">
           <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="{{route('home')}}" class="breadcrumb-link">Dashboard</a></li>
               <li class="breadcrumb-item"><a href="{{route('organization.index')}}" class="breadcrumb-link">Organizations</a></li>
               <li class="breadcrumb-item"><a href="" class="breadcrumb-link">{{$organization->name}}</a></li>
           </ol>
       </nav>
   </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @csrf
                <div class="card-header"> {{$organization->name}}
                    <div class="float-right">
                        <a href="{{route('organization.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                        <a href="{{route('organization.edit',$organization->id)}}" class="btn btn-sm btn-outline-primary">Edit</a>
                    </div>
                </div>
                <div class="">
                    <table class="table">
                        <tr>
                            <th>Name</th>
                            <td>{{$organization->name}}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{$organization->type}}</td>
                        </tr>
                        <tr>
                            <th>Location</th>
                            <td>{{$organization->location}}</td>
                        </tr>
                        <tr>
                            <th>Point of Contact</th>
                            <td>
                                @if ($organization->Person)
                                    {{$organization->Person->name}}
                                @else
                                No Contact attached
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{$organization->email}}</td>
                        </tr>
                        <tr>
                            <th>Phone</th>
                            <td>{{$organization->phone}}</td>
                        </tr>
                        <tr>
                            <th>Tags</th>
                            <td>
                                @forelse (explode(",",$organization->tags) as $item)
                                    <span class="badge badge-success">{{$item}}</span>
                                @empty
                                    
                                @endforelse
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="card">
                <div class="card-header">People in {{$organization->name}} </div>
                <div class="">
                    <table class="table table-sm">
                        <thead class="table-secondary">
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Position</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($organization->Employees as $employee)
                                <tr>
                                    <th><a href="{{route('people.show',$employee->id)}}">{{$employee->name}}</a></th>
                                    <td>{{$employee->email}}</td>
                                    <td>{{$employee->mobile}}</td>
                                    <td>{{$employee->Category->category}} ({{$employee->position}})</td>
                                </tr>
                            @empty
                                <tr>
                                    <th colspan="4" class="text-center">No people attached to this organization</th>
                                </tr>
                            @endforelse
                    </table>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Events By {{$organization->name}} </div>
                <div class="">
                    <table class="table table-sm">
                        <thead class="table-secondary">
                            <tr>
                                <th>Events</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($organization->Events as $event)
                                <tr>
                                    <th><a href="{{route('events.show',$event->id)}}">{{$event->name}}</a></th>
                                </tr>
                            @empty
                                <tr>
                                    <th colspan="4" class="text-center">No people attached to this organization</th>
                                </tr>
                            @endforelse
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection