routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::any('/register', 'HomeController@index')->name('register');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'Search@search')->name('search');
Route::post('/search', 'Search@search')->name('search');
Route::get('/search-more', 'Search@searchaction')->name('searchaction');
Route::post('/search', 'Search@search')->name('search');
Route::resource('/tags', 'TagsController');
Route::resource('/staff', 'UserController');
Route::resource('/people', 'PersonController');
Route::resource('/contact-categories', 'PersonTypeController');
Route::resource('/organization', 'OrganizationController');
Route::resource('/events', 'EventController');
Route::resource('/skills', 'SkillController');
Route::resource('/interests', 'InterestController');
Route::resource('/event/event-dates', 'EventDateController');
Route::get('/event/event-date/export/attendees/{event}', 'EventDateController@export')->name('export-event-attendees');
Route::post('/event/event-date/spot/attendees/{event}', 'EventDateController@spot')->name('attendance.spot');
Route::resource('/event-date/attendance', 'EventAttendanceController');
Route::resource('/event-date/speakers', 'EventSpeakersController');
Route::resource('settings', 'SettingsController');

// Excel Import

Route::post('/import/people', 'PersonController@import')->name('people.import');
Route::post('/import/organizations', 'OrganizationController@import')->name('organization.import');
Route::post('/import/events', 'EventController@import')->name('event.import');
Route::post('/import/event-dates', 'EventDateController@import')->name('event-dates.import');
Route::post('/import/event-dates/attendance', 'EventAttendanceController@import')->name('event-dates.attandance.import');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    public function Organizer()
    {
        return $this->hasOne('App\Organization', 'id','organization');
    }
    public function Dates()
    {
        return $this->hasMany('App\EventDate', 'event','id');
    }
    public function Tags()
    {
        $tag = "";
        foreach (explode(",",$this->tags) as $item) {
            $tag .= "<span class=\"badge badge-success\">$item</span>";
        }
        return $tag;
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Organization;
use App\tags;
use Illuminate\Http\Request;
use Importer;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::paginate(10);
        return view('event.index',['events'=>$events]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organizations = Organization::all();
        return view('event.create',['organizations'=>$organizations]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([
            'name'=>'required|string|max:255',
            'organization'=>'required|string|max:255',
            'tags'=>'string|max:255',
        ]);

        $event       = new Event;
        $event->name = $request->name;
        $event->organization = $request->organization;
        $event->tags = $request->tags;
        $event->save();
        return redirect()->back()->with(['success'=>"New Event:  $event->name ."]);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        $organizations = Organization::all();
        return view('event.show',['event'=>$event,"organizations"=>$organizations]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
       $request->validate([
            'name'=>'required|string|max:255',
            'organization'=>'required|string|max:255',
            'tags'=>'string|max:255',
        ]);

        $event->name = $request->name;
        $event->organization = $request->organization;
        $event->tags = $request->tags;
        foreach(explode(',',$request->tags) as $tag){
            $fs = tags::where('tag',$tag)->first();
            if(!$fs){
                $fd = new tags;
                $fd->tag = $tag;
                $fd->save();
            }
        }
        $event->save();
        return redirect()->back()->with(['success'=>"Update Success."]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        //
    }
   public function import(Request $request)
    {
        $file   = $request->file('upload');
        $fl     = $file->move('storage/temp',$file->getClientOriginalName());
        $excel = Importer::make('Excel');
        $excel->load($fl);
        $collection = $excel->getCollection();
        $fields     = $collection[0];
        $data       = [];
        for ($i=1; $i <count($collection) ; $i++) {
            $data[$i] = [];
            for ($s=0; $s <count($fields) ; $s++) {
                $data[$i][$fields[$s]] = $collection[$i][$s];
            }
        }
        foreach($data as $dat){
            $event = new Event;
            foreach ($dat as $key => $value) {
                if($key == 'organization'){
                    $ps = Organization::where('name',$value)->first();
                    if($ps){
                        $event->{$key} = $ps->id;
                    }
                }
                elseif($key == 'tags'){
                    $key = trim($key);
                    foreach(explode(',',$value) as $tag){
                        $fs = tags::where('tag',$tag)->first();
                        if(!$fs){
                            $fd = new tags;
                            $fd->tag = $tag;
                            $fd->save();
                        }
                    }
                    $event->{$key} = $value;
                }
                else{
                    $event->{$key} = $value;
                }
            }
            $event->save();
        }
        unlink($fl);
        return redirect()->back()->with('success', 'Upload and Import Sucess!');
    }
}

resources/views/event/create.blade.php
@extends('layouts.internal')
@section('title',"Add new Event")
@section('content')
<div class="container">
    <div class="py-4"></div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="card" action="{{route('events.store')}}" method="POST">
                @csrf
                <div class="card-header">Create events
                    <div class="float-right">
                        <a href="{{route('events.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
                    </div>
                </div>
                <div class="card-body row">
                    <div class="form-group col-sm-12">
                        <label for="org_name">Name</label>
                        <input type="text" name="name" id="org_name" class="form-control" value="@if(old('name')) {{old('name')}} @endif">
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="org_tags">Tags</label>
                        <input type="text" name="tags" id="org_tags" class="form-control typeahead" value="@if(old('tags')) {{old('tags')}} @endif">
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="organization">Organizer</label>
                        <select name="organization" id="organization" class="form-control selectjs-basic-single" required>
                            @forelse ($organizations as $organization)
                                <option @if(old('organization') == $organization->id) selected @endif value="{{$organization->id}}">{{$organization->name}}</option>
                            @empty
                                <option selected disabled >No Organizations available.</option>
                            @endforelse
                        </select>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success btn-sm float-right">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/event/index.blade.php
@extends('layouts.internal')
@section('title',"Events")
@section('content')
<div class="page-header">
    <h3 class="mb-2">Events <i>({{$events->count()}})</i></h3>
    <div class="page-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}" class="breadcrumb-link">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Events</a></li>
            </ol>
        </nav>
    </div>
 </div>

 <div class="container">
     <div class="row">
         <div class="col-sm-12 col-md-10 ">
            <div class="card table-responsive">
                <table class="table table-sm">
                    <thead class="table-secondary">
                        <tr>
                            <th>Name</th>
                            <th>Organizer</th>
                            <th>Tags</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($events as $event)
                        <tr>
                            <td><a href="{{route('events.show',$event->id)}}">{{$event->name}}</a></td>
                            <td><a href="{{route('organization.show',$event->Organizer->id)}}">{{$event->Organizer->name}}</a></td>
                            <td>{!!$event->Tags()!!}</td>
                        </tr>
                        @empty
                        <tr><th colspan="4" class="text-center">No Events</th></tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="py-1"></div>
                <div class="card-footer">
                    {{$events->links()}}
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-2">
            <div class="card card-body">
                 <a href="{{route('events.create')}}" class="btn btn-sm btn-outline-secondary">Create New</a> 
                 <br>
                 <a href="#event-upload-modal" data-toggle="modal" data-target="#event-upload-modal" class="btn btn-sm btn-outline-primary">Upload CSV</a>
            </div>
        </div>
     </div>
 </div>
    <form action="{{route('event.import')}}" method="POST" class="modal" id="event-upload-modal" enctype="multipart/form-data">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    @csrf
                <div class="form-group">
                    <input type="file" accept=".csv" required  name="upload" class="form-control">
                </div>
                <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Cancel</button>
                <button class="btn btn-info btn-sm" type="submit">Upload</button>
            </div>
        </div>
    </form>

@endsection

resources/views/event/show.blade.php
@extends('layouts.internal')
@section('title',$event->name)
@section('content')
<div class="page-header">
    <h3 class="mb-2">{{$event->name}}</h3>
    <div class="page-breadcrumb">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('home')}}" class="breadcrumb-link">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{route('events.index')}}" class="breadcrumb-link">Events</a></li>
                <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">{{$event->name}}</a></li>
            </ol>
        </nav>
    </div>
 </div>
 <div class="container">
    <div class="row">

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-inline-block">
                        <h5 class="text-muted">Total Dates</h5>
                        <h2 class="mb-0">{{$event->Dates->count()}} </h2>
                    </div>
                    <div class="float-right icon-circle-medium  icon-box-lg  bg-primary-light mt-1">
                        <i class="material-icons text-primary">calendar_today</i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12"></div>
        <div class="col-sm-12 col-md-6">
            <div class="card table-responsive">
                <div class="card-header">
                    <a href="{{route('event-dates.create',['event'=>$event->id])}}" class="btn btn-xs btn-outline-danger float-right">Add New Date</a>
                    Event Dates
                </div>
                <table class="table table-xs">
                    @forelse ($event->Dates as $dates)
                    <tr>
                        <th> <a href="{{route('event-dates.show',$dates->id)}}">{{$dates->isDate()}}, {{$dates->venue}} </a></th>
                    </tr>
                    @empty
                        <th class="text-center" colspan="2">No Dates Announced</th>
                    @endforelse
                </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="card table-responsive">
                <div class="card-header">
                    <a href="#edit-event" data-toggle="modal" data-target="#edit-event" class="btn btn-xs btn-outline-danger float-right">Edit</a>
                    About Event
                </div>
                <table class="table table-xs">
                    <tbody>
                        <tr>
                            <th>Event Name</th>
                            <td>{{$event->name}}</td>
                        </tr>
                        <tr>
                            <th>Event Organizer</th>
                            <td><a href="{{route('organization.show',$event->Organizer->id)}}">{{$event->Organizer->name}}</a></td>
                        </tr>
                        <tr>
                            <th>Tags</th>
                            <td>{!!$event->Tags()!!}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-2 ">
            <div class="card card-body">
                <a href="{{route('events.index')}}" class="btn btn-sm btn-outline-secondary">Back to List</a>
            </div>
        </div>
    </div>
 </div>
 <div class="modal" id="edit-event">
     <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                @include('event.inc.edit')
            </div>
        </div>
     </div>
 </div>
@endsection